version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: docker.io/library/postgres:13
    environment:
      - POSTGRES_DB=flathub_webhook_proxy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
